### 1. What is a Python library? Why do we use Python libraries?

In [1]:
### python library : library is nothing but a file which file is created by a some developer
###                  file contains classes and classes contain number of functions .. this is about library
## why we use this libraris >>  efficience of code and functionailty and reliablity  and standardization and community support


### 2. What is the difference between Numpy array and List?

In [2]:
## differences between numpy array and list : 
#                                      numpy array stores homogenous data and list stores heterogenous data
#                                      numpy array is very fast compare with list because numpy array built with c++ language so it is very fast
#                                      syntax : numpy.array() , list()
#                                      numpy has wide range of mathemetical functions but list not

### 3. Find the shape, size and dimension of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]] 

In [3]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("shape is : ", arr.shape)
print("size is : ",arr.size)
print("dimensions : ",arr.ndim)

shape is :  (3, 4)
size is :  12
dimensions :  2


### 4. Write python code to access the first row of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print("first row : ",arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first row :  [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("element at the third row and fourth column : ",arr[2][3])

element at the third row and fourth column :  12


### 6. Write code to extract all odd-indexed elements from the given numpy array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
## by using random module
arr = np.random.rand(3,3)
arr

array([[0.77789725, 0.34958094, 0.58081874],
       [0.28730007, 0.91898436, 0.70306545],
       [0.98401132, 0.85362783, 0.16030345]])

### 8. Describe the difference between np.random.rand and np.random.randn?

In [8]:
# the main difference between is >> 
#                                 np.random.rand : generates ranodm numbers from uniform distribution over the interval[0,1)
#                                 np.random.randn : generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). 
                                                                                                                      

### 9. Write code to increase the dimension of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [9]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("previous dimension : ",arr.ndim)
arr_n = np.expand_dims(arr,axis=0)

print("after expanding dimensions : ",arr_n.ndim)

previous dimension :  2
after expanding dimensions :  3


### 10. How to transpose the following array in NumPy?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr.T  

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 11. Consider the following matrix:
### Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Perform the following operation using Python:

#### Index wise multiplication

In [13]:
matrix1 = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix2 = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("matrix1 : ")
print(matrix1)
print("matrix2 : ")
print(matrix2)
print("index multiplication : ")
print(np.array(matrix1)*np.array(matrix2))

matrix1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matrix2 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
index multiplication : 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


##### Matix multiplication

In [15]:
matrix1*matrix2.T

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

##### 3) Add both the matics

In [16]:
matrix1+matrix2

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

##### 4) Subtract matrix B from A

In [17]:
matrix2-matrix1

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

#### Divide Matrix B by A

In [18]:
matrix2/matrix1

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### 12. Which function in Numpy can be used to swap the byte order of an array?

In [21]:
## we have to use the byteswap function to swap the array in byte case
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap byte order
arr_swapped = arr.byteswap()

print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)


Original array: [1 2 3 4]
Array with swapped byte order: [16777216 33554432 50331648 67108864]


### 13. What is the significance of the np.linalg.inv function?

In [29]:

# The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. 
# In other words, it calculates the inverse of a square matrix.
# The significance of this function lies in various mathematical and computational applications, 
# particularly in solving systems of linear equations and in linear algebra operations

# arr1 = np.array([[1,2],[2,4]])
# arr2 = np.array([2,5])

# np.linalg.inv(arr1).dot(arr2)
import numpy as np

# Define coefficient matrix A
A = np.array([[2, 3], [1, -2]])

# Define constant vector b
b = np.array([8, -3])

# Solve for variables x
x = np.linalg.inv(A).dot(b)

print("Solution:", x)


Solution: [1. 2.]


### 14. What does the np.reshape function do, and how is it used?

In [30]:
# reshape function is used to reshape the array without changing the data , it allows you to rearrange the 
# elements of a new shape, provided that the total number of elements remains the same.

arr = np.array([[1,2,3,4],[5,6,4,3]])
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 3]])

### 15. What is broadcasting in python?


In [34]:
# broadcasting nothing but a when we are doing operations with an array then 
# is applying to all elements in array is known as broadcasting

## example
arr = np.array([[1,2,3,4],[9,8,7,6],[0,0,0,0]])
print("Before broadcasting : ")
print(arr)
print("After broadcasting : ")
print(arr+3)

Before broadcasting : 
[[1 2 3 4]
 [9 8 7 6]
 [0 0 0 0]]
After broadcasting : 
[[ 4  5  6  7]
 [12 11 10  9]
 [ 3  3  3  3]]
